CREATE TABLE IF NOT EXISTS movies (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  director VARCHAR(50) NOT NULL,
  release_year INT NOT NULL,
  duration VARCHAR(7) NOT NULL,
  imdb_link VARCHAR(100) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,

  UNIQUE (title, release_year)
);
