CREATE TABLE IF NOT EXISTS halls(
  id SERIAL PRIMARY KEY,
  theater_id INT NOT NULL REFERENCES theaters(id) ON DELETE CASCADE,
  name VARCHAR(30) NOT NULL,
  code VARCHAR(10) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

  UNIQUE (theater_id, code)
);
