CREATE TABLE IF NOT EXISTS movies (
  imdb_id VARCHAR(12) PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  year INT NOT NULL,
  rated VARCHAR(10) NOT NULL,
  runtime VARCHAR(10) NOT NULL,
  genre VARCHAR(50) NOT NULL,
  director VARCHAR(50) NOT NULL,
  poster VARCHAR(100) NOT NULL,
  imdb_rating DECIMAL(3, 1) NOT NULL,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
);
