CREATE TABLE IF NOT EXISTS shows (
  id SERIAL PRIMARY KEY,
  movie_id VARCHAR(12) NOT NULL REFERENCES movies(imdb_id),
  hall_id INT NOT NULL REFERENCES halls(id),
  start_time TIMESTAMP WITH TIME ZONE NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE NOT NULL,

  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
);
